models:
  llama3:
    source: 'local'
    model_type: 'lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF'
    base_url: 'http://localhost:1234/v1'
    api_key: 'lm-studio'
  gpt35:
    source: 'openai'
    model_type: 'gpt-3.5-turbo'
  gpt4:
    source: 'openai'
    model_type: 'gpt-4-turbo-preview'
personas:
  supporter_ai: 'gpt35'
  rude_ai: 'gpt35'
  sage_ai: 'gpt35'
  # challenger_ai: 'gpt35'
